FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019

# Set the working directory
WORKDIR /inetpub/wwwroot

# Copy the published application
COPY ./WebAPI/WebApplication1/ ./

# Expose port 80
EXPOSE 80

# The base image already has IIS configured
